name: Younique Film
favicon: null
layout_spectrum: 0.835003798129037
typography_spectrum: 0.9231560763437301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#526778'
    - '#7d96a8'
    - '#edecea'
    - '#fd5655'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
